### ISSUE TITLE
Required Changes for the MarketPlace Contract

### ISSUE THREAD

**Issue by ro61zzy** [michojekunle/Vintage-Car-Marketplace#46]
**Description:**

### File: [`MarketPlace.sol`](https://github.com/michojekunle/Vintage-Car-Marketplace/blob/main/smart-contracts/contracts/MarketPlace.sol)

**Points to address:**

1. **Interaction with `SellerVerification` and `CarVerification` contracts:**
   - Important: add a check to ensure that the seller attempting to list a car is verified. The verification process should also include checking the Vehicle Identification Number (VIN) and any relevant details to confirm the vehicle is authentic and verified.
   
   _Suggested Action:_ Implement validation to ensure that both the seller and the car pass verification before proceeding with any listings.

2. **Auction Contract Interaction:**
   - How does this contract interact with the auction contract? At what point does the auctioning process come into play?
   
   @Tchisom17, could you please comment on this

3. **Compatibility with the NFT Contract:**
   - Will this contract integrate seamlessly with the existing NFT contract? NFT contract easily interface with this marketplace.
   
   @DonGuillotine,

**Comment by DonGuillotine** [comment]
> **Description:**
> 
> ### File: [`MarketPlace.sol`](https://github.com/michojekunle/Vintage-Car-Marketplace/blob/main/smart-contracts/contracts/MarketPlace.sol)
> **Points to address:**
> 
> 1. **Interaction with `SellerVerification` and `CarVerification` contracts:**
>    
>    * Important: add a check to ensure that the seller attempting to list a car is verified. The verification process should also include checking the Vehicle Identification Number (VIN) and any relevant details to confirm the vehicle is authentic and verified.
>    
>    _Suggested Action:_ Implement validation to ensure that both the seller and the car pass verification before proceeding with any listings.
> 2. **Auction Contract Interaction:**
>    
>    * How does this contract interact with the auction contract? At what point does the auctioning process come into play?
>    
>    @Tchisom17, could you please comment on this
> 3. **Compatibility with the NFT Contract:**
>    
>    * Will this contract integrate seamlessly with the existing NFT contract? NFT contract easily interface with this marketplace.
>    
>    @DonGuillotine,

All done, I updated the contract -> https://github.com/michojekunle/Vintage-Car-Marketplace/pull/51/files

**Comment by michojekunle** [comment]
Closing Issue:

Issue fixed at PR https://github.com/michojekunle/Vintage-Car-Marketplace/pull/51
