### ISSUE TITLE
NFT Contract as ERC721URIStorage to set token URI

### ISSUE THREAD

**Issue by yusufroqib** [michojekunle/Vintage-Car-Marketplace#67]
### File: [VintageCarNFT.sol](https://github.com/michojekunle/Vintage-Car-Marketplace/blob/main/smart-contracts/contracts/VintageCarNFT.sol)

I just checked the Updated NFT Contract. We're not using standard **ERC721URIStorage**. To set tokenURI. Also, we don't need to verify car or  add **isVerified** in the NFT contract. We can have a variable which is address of our **car verification contract**. Then we pass in the interface to interact with the external contract to check if caller is verified before minting. Also, it's the person that adds cars that should mint, not us. The mint function will have an extra argument which is the vin. Which we'll use to query the car **verification contract.** 
We can have _**mapping of vin to tokenid**_ to keep track of the relationship

**Comment by yusufroqib** [comment]
@michojekunle can you check this out?

**Comment by yusufroqib** [comment]
We can have mapping of vin to tokenid to keep track of the relationship

**Comment by yusufroqib** [comment]
Here is a sample snippet from openzepellin wizard
```solidity
// SPDX-License-Identifier: MIT
// Compatible with OpenZeppelin Contracts ^5.0.0
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721Enumerable.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721Pausable.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

contract MyToken is ERC721, ERC721Enumerable, ERC721URIStorage, ERC721Pausable, Ownable {
    constructor(address initialOwner)
        ERC721("MyToken", "MTK")
        Ownable(initialOwner)
    {}

    function pause() public onlyOwner {
        _pause();
    }

    function unpause() public onlyOwner {
        _unpause();
    }

    function safeMint(address to, uint256 tokenId, string memory uri)
        public
        onlyOwner
    {
        _safeMint(to, tokenId);
        _setTokenURI(tokenId, uri);
    }

    // The following functions are overrides required by Solidity.

    function _update(address to, uint256 tokenId, address auth)
        internal
        override(ERC721, ERC721Enumerable, ERC721Pausable)
        returns (address)
    {
        return super._update(to, tokenId, auth);
    }

    function _increaseBalance(address account, uint128 value)
        internal
        override(ERC721, ERC721Enumerable)
    {
        super._increaseBalance(account, value);
    }

    function tokenURI(uint256 tokenId)
        public
        view
        override(ERC721, ERC721URIStorage)
        returns (string memory)
    {
        return super.tokenURI(tokenId);
    }

    function supportsInterface(bytes4 interfaceId)
        public
        view
        override(ERC721, ERC721Enumerable, ERC721URIStorage)
        returns (bool)
    {
        return super.supportsInterface(interfaceId);
    }
}

```

**Comment by DonGuillotine** [comment]
> ### File: [VintageCarNFT.sol](https://github.com/michojekunle/Vintage-Car-Marketplace/blob/main/smart-contracts/contracts/VintageCarNFT.sol)
> I just checked the Updated NFT Contract. We're not using standard **ERC721URIStorage**. To set tokenURI. Also, we don't need to verify car or add **isVerified** in the NFT contract. We can have a variable which is address of our **car verification contract**. Then we pass in the interface to interact with the external contract to check if caller is verified before minting. Also, it's the person that adds cars that should mint, not us. The mint function will have an extra argument which is the vin. Which we'll use to query the car **verification contract.** We can have _**mapping of vin to tokenid**_ to keep track of the relationship

@yusufroqib I have implemented the enhancements here -> https://github.com/michojekunle/Vintage-Car-Marketplace/pull/69

**Comment by michojekunle** [comment]
Closing issue --- Issue fixed at @yusufroqib I have implemented the enhancements here -> https://github.com/michojekunle/Vintage-Car-Marketplace/pull/69
