### ISSUE TITLE
Marketplace Contract Corrections 

### ISSUE THREAD

**Issue by yusufroqib** [michojekunle/Vintage-Car-Marketplace#68]
### File: [VintageCarMarketplace.sol](https://github.com/michojekunle/Vintage-Car-Marketplace/blob/main/smart-contracts/contracts/VintageCarMarketplace.sol)

In the marketplace itself, I saw places where we used

```solidity
(, , , string memory vin, , , ,) = vintageCarNFT.getCarDetails(tokenId);

carVerificationOracle.transferOwnership(vin, buyer);
```

I think they are no longer needed. Since NFT for a vin can only be minted once. Once NFT is transferred, ownership is also transferred right? Also, we don't actually need to transferOwnership in the carVerification contract from our Marketplace contract. 

Also, we don't need extra check if a car is verified or not. Once there is an NFT, it means the car is already verified in the NFT contract before minting

**Comment by yusufroqib** [comment]
@DonGuillotine @michojekunle

**Comment by michojekunle** [comment]
Yes actually means we don't also need to check for ownership from the nft contract when listing we're just going to be transferring nft as proof of ownership that's all @DonGuillotine ... right @yusufroqib
